Bootstrap: docker
From: staphb/prokka:1.14.5

%labels
    Maintainer icaoberg
    EMAIL icaoberg@psc.edu
    REPOSITORY https://github.com/pscedu/singularity-prokka
    COPYRIGHT Copyright © 2021 Pittsburgh Supercomputing Center. All Rights Reserved. 
    VERSION 1.14.5

%post
#   rm /etc/resolv.conf

####################################################################################
